### ISSUE TITLE
Exporting the getPorts function in rdma_map.go

### ISSUE THREAD

**Issue by willfurnell** [Mellanox/rdmamap#2]
Hi,

Is there a specific reason why getPorts is not exported in rdma_map? It would be rather useful to have it exported there so ports can be iterated over when looking at statistics in a separate program.

Thanks,

Will.

**Comment by moshe010** [comment]
I don't this there is a reason for it to be internal, you are welcome to push PR to fix this

**Comment by willfurnell** [comment]
I've made a PR for this #3

**Comment by moshe010** [comment]
closing this issue as PR #3 is merged.
